CREATE TABLE IF NOT EXISTS coffee(
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            coffee_count int,
            milk_count int,
            operation VARCHAR(100)
);

insert into coffee values (1, 500, 0, 'Add coffee');
insert into coffee values (2, 500, 1000, 'Add milk');